language: r
r:
  - release
  - devel
cache: packages
addons:
  apt:
    packages:
      - gcc
github_packages:
  - r-lib/covr
script:
  - |
    R CMD build .
    travis_wait 30 R CMD check mkin_*.tar.gz
after_success:
  - Rscript -e 'covr::codecov()'
